## EntitySpriteCatalog — resolves an [EntityState] to its runtime sprite texture
## path, Presentation layer (Story 006 / sprint task S5-01).
##
## The ONE place the art-bible §8.2 naming convention is spelled out in code. Kept
## separate from [BoardRenderer] and [EntitySpriteFeed] deliberately: path
## resolution is pure string work with no scene tree, so it is unit-testable
## without instantiating a node, and a naming-convention change touches exactly one
## file. Every method is [code]static[/code] — this class is never instantiated.
##
## [b]The load contract lives in [code]assets/art/README.md[/code][/b] and carries
## three rules that silently break rendering if missed. Two are enforced here (the
## facing map, the naming convention); the third (2x textures) is
## [EntitySpriteFeed]/[BoardRenderer]'s.
##
## [b]Faction identity is compared BY REFERENCE[/b] against the [Factions]
## registry constants, not by a name string — [FactionDef] is still ADR-0012's
## forward-declared stub and carries no id field at all (see
## [code]faction_def.gd[/code]). [method faction_token] is therefore the single
## adapter between faction identity and the art tree; when ADR-0012's real schema
## lands with a proper id, this method is the only thing that changes.
##
## Usage:
## [codeblock]
## var path := EntitySpriteCatalog.texture_path(entity, faction, "e")
## # -> "res://assets/art/units/unit_scout_rush_e_idle_01.png"
## [/codeblock]
class_name EntitySpriteCatalog
extends RefCounted

## Runtime art roots. [code]assets/art/[/code] is GENERATED by
## [code]tools/asset-pipeline/place_runtime.py[/code] — never hand-edit a file
## there; edit the master in [code]art-source/[/code] and re-run, or the change is
## lost on the next pass (assets/art/README.md).
const UNITS_DIR: String = "res://assets/art/units/"

## See [constant UNITS_DIR].
const STRUCTURES_DIR: String = "res://assets/art/structures/"

## See [constant UNITS_DIR].
const TERRAIN_DIR: String = "res://assets/art/terrain/"

## The faction token for an unowned/menu entity, and the fallback when a
## [FactionDef] matches no [Factions] registry constant. Neutral art ships for
## every unit and structure, so this fallback always resolves to a real file.
const NEUTRAL_TOKEN: String = "neutral"

## The two authored facings (assets/art/README.md). Bare SDXL cannot rotate a
## specific design, so [code]n[/code] and [code]s[/code] are NOT authored — they
## map onto these two by the sign of screen-x travel ([method facing_for_delta]).
const FACING_EAST: String = "e"

## See [constant FACING_EAST].
const FACING_WEST: String = "w"

## The facing a newly-appeared entity carries until it first moves. Units are
## produced onto the board without any travel to take a sign from, so there is no
## derivable answer — [constant FACING_EAST] is a deliberate arbitrary pick, not a
## computed one.
##
## [b]Unpinned feel value[/b]: whether a fresh unit should instead face the
## opponent's side of the board is a design/feel call for the S5-03 legibility
## pass, not a correctness one — both facings are legal art.
const DEFAULT_FACING: String = FACING_EAST

## The [code]state[/code] token for a live entity (art-bible §8.5). The
## AP-available and AP-spent idles deliberately share ONE texture — the difference
## is [code]pulse_intensity[/code] on the glow shader (S5-02), never a second pose.
const STATE_IDLE: String = "idle"

## The [code]state[/code] token for an entity at or below zero hp.
##
## [b]⚠ Not reachable from a live [method GameState.entities] feed today.[/b]
## [method GameState.destroy_entity] erases the entity from
## [code]entities_by_id[/code] in the same frame its hp hits zero, so a destroyed
## entity never appears in a feed snapshot — it simply vanishes. This token is
## resolved correctly here (Story 006 AC-10) but nothing puts it on screen until
## S5-06 adds the death-echo hold that keeps the node alive for §8.5's 2-4 frame
## beat. Recorded rather than hidden: S5-06 is load-bearing for AC-10.
const STATE_DESTROYED: String = "destroyed"


## Maps a [FactionDef] to its art-tree faction token ([code]rush[/code] /
## [code]boom[/code] / [code]neutral[/code]). Compared by reference against the
## [Factions] registry constants — see the class doc comment for why an id string
## is not available. An unrecognised or [code]null[/code] faction resolves to
## [constant NEUTRAL_TOKEN] rather than erroring: neutral art ships for every
## asset, so this degrades to a real texture instead of a blank sprite.
static func faction_token(faction: FactionDef) -> String:
	if faction == Factions.RUSH:
		return "rush"
	if faction == Factions.BOOM:
		return "boom"
	return NEUTRAL_TOKEN


## Converts a [member UnitTypeDef.display_name]/[member StructureTypeDef.display_name]
## to its art-tree type token: lowercased, spaces to underscores
## ([code]"Production Outpost" -> "production_outpost"[/code]). The display name is
## the only type identity either def carries — neither has a separate id field —
## so this is the adapter between the balance data and the art tree.
static func type_token(display_name: String) -> String:
	return display_name.to_lower().replace(" ", "_")


## Picks the authored facing for a grid-space movement [param delta] by the SIGN OF
## SCREEN-X TRAVEL (assets/art/README.md), which for the 2:1 dimetric projection is
## the sign of [code]delta.x - delta.y[/code] — [method BoardRenderer.grid_to_screen]'s
## x term is [code](tile.x - tile.y) * TILE_WIDTH_PX * 0.5[/code], so the tile
## dimensions cancel out of the comparison entirely.
##
## This reproduces the README's facing table exactly:
## [codeblock]
## n (0,-1) -> dx-dy = +1 -> e     e (1,0)  -> dx-dy = +1 -> e
## s (0, 1) -> dx-dy = -1 -> w     w (-1,0) -> dx-dy = -1 -> w
## [/codeblock]
## A [param delta] with no screen-x component (pure-diagonal travel, or no travel)
## returns [param previous_facing] — facing never flips arbitrarily on a move that
## carries no left/right information.
static func facing_for_delta(delta: Vector2i, previous_facing: String) -> String:
	var screen_dx: int = delta.x - delta.y
	if screen_dx > 0:
		return FACING_EAST
	if screen_dx < 0:
		return FACING_WEST
	return previous_facing


## The art-bible §8.5 state token for [param entity] — [constant STATE_DESTROYED]
## at or below zero hp, else [constant STATE_IDLE]. Reads [code]current_hp[/code]
## off [UnitState]/[StructureState]; a bare [EntityState] (no hp field) is always
## idle. See [constant STATE_DESTROYED] for why the destroyed branch is currently
## unreachable from a live feed.
static func state_token(entity: EntityState) -> String:
	if entity is UnitState and (entity as UnitState).current_hp <= 0:
		return STATE_DESTROYED
	if entity is StructureState and (entity as StructureState).current_hp <= 0:
		return STATE_DESTROYED
	return STATE_IDLE


## Resolves the full [code]res://[/code] texture path for [param entity] owned by
## [param faction] and drawn at [param facing], per the art-bible §8.2 convention:
## [codeblock]
## units:      unit_[archetype]_[faction]_[facing]_[state]_[frame].png
## structures: struct_[name]_[faction]_[state].png
## [/codeblock]
## Structures carry no facing and no frame token — they are authored one-per-hue
## and never turn. Only frame [code]01[/code] exists for every unit state
## (assets/art/README.md); there are no multi-frame sheets.
##
## Returns an empty [String] for an entity that is neither a [UnitState] nor a
## [StructureState] — the caller (see [method EntitySpriteFeed._texture_for])
## treats that as the same explicit-failure case as a missing file, never as a
## blank sprite (Story 006 QA: "missing texture errors explicitly").
static func texture_path(entity: EntityState, faction: FactionDef, facing: String) -> String:
	var faction_str: String = faction_token(faction)
	var state: String = state_token(entity)
	if entity is UnitState:
		var unit_type: UnitTypeDef = (entity as UnitState).type
		if unit_type == null:
			return ""
		var archetype: String = type_token(unit_type.display_name)
		return "%sunit_%s_%s_%s_%s_01.png" % [UNITS_DIR, archetype, faction_str, facing, state]
	if entity is StructureState:
		var struct_type: StructureTypeDef = (entity as StructureState).type
		if struct_type == null:
			return ""
		var struct_name: String = type_token(struct_type.display_name)
		return "%sstruct_%s_%s_%s.png" % [STRUCTURES_DIR, struct_name, faction_str, state]
	return ""
